logging:
  level:
    root: DEBUG

spring:
  config:
    import: file:.env[.properties]
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true