name: Run all tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests with gradle
        run: ./gradlew test

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup chromium
        run: sudo apt install chromium && echo "CHROME_BIN=$(which chromium)" >> $GITHUB_ENV

      - name: Install node packages
        working-directory: web
        run: npm ci

      - name: Run frontend tests
        working-directory: web
        run: npm run test

